### Prostate Cancer

In [10]:
import pandas as pd
import numpy as np

In [11]:
prostate_cancer = pd.read_csv("/Users/maddiemann/Documents/MATH-4025-sp26/Math-4025-Project-Maddie-Mann/Data/prad_tcga_pan_can_atlas_2018_clinical_data.tsv", sep='\t')

In [12]:
prostate_cancer.head()

,Study ID,Patient ID,Sample ID,Diagnosis Age,Neoplasm Disease Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Publication Version Type,Aneuploidy Score,Buffa Hypoxia Score,Cancer Type,TCGA PanCanAtlas Cancer Type Acronym,...,Tumor Break Load,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site,Tissue Source Site Code,TMB (nonsynonymous),Tumor Disease Anatomic Site,Tumor Type,Patient Weight,Winter Hypoxia Score
0,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VL,TCGA-2A-A8VL-01,51,NaN,NaN,0.0,-27.0,Prostate Cancer,PRAD,...,50.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.7,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-34.0
1,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VO,TCGA-2A-A8VO-01,57,NaN,NaN,0.0,-29.0,Prostate Cancer,PRAD,...,32.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.9,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-26.0
2,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VT,TCGA-2A-A8VT-01,47,NaN,NaN,14.0,-39.0,Prostate Cancer,PRAD,...,29.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.3,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-42.0
3,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VV,TCGA-2A-A8VV-01,52,NaN,NaN,0.0,-25.0,Prostate Cancer,PRAD,...,25.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.8,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-36.0
4,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VX,TCGA-2A-A8VX-01,70,NaN,NaN,2.0,NaN,Prostate Cancer,PRAD,...,149.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.0,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,NaN

In [13]:
prostate_cancer.columns = prostate_cancer.columns.str.replace(' ', '_')

In [26]:
prostate_cancer.columns

Index(['Study_ID', 'Patient_ID', 'Sample_ID', 'Diagnosis_Age',
       'Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code',
       'American_Joint_Committee_on_Cancer_Publication_Version_Type',
       'Aneuploidy_Score', 'Buffa_Hypoxia_Score', 'Cancer_Type',
       'TCGA_PanCanAtlas_Cancer_Type_Acronym', 'Cancer_Type_Detailed',
       'Last_Communication_Contact_from_Initial_Pathologic_Diagnosis_Date',
       'Birth_from_Initial_Pathologic_Diagnosis_Date',
       'Last_Alive_Less_Initial_Pathologic_Diagnosis_Date_Calculated_Day_Value',
       'Disease_Free_(Months)', 'Disease_Free_Status',
       'Months_of_disease-specific_survival',
       'Disease-specific_Survival_status', 'Ethnicity_Category',
       'Form_completion_date', 'Fraction_Genome_Altered',
       'Genetic_Ancestry_Label', 'Neoplasm_Histologic_Grade',
       'Neoadjuvant_Therapy_Type_Administered_Prior_To_Resection_Text',
       'ICD-10_Classification',
       'International_Classification_of_Diseases_for_Oncology,_Third_Edition_ICD-O-3_Histology_Code',
       'International_Classification_of_Diseases_for_Oncology,_Third_Edition_ICD-O-3_Site_Code',
       'Informed_consent_verified', 'In_PanCan_Pathway_Analysis',
       'MSI_MANTIS_Score', 'MSIsensor_Score', 'Mutation_Count',
       'New_Neoplasm_Event_Post_Initial_Therapy_Indicator', 'Oncotree_Code',
       'Overall_Survival_(Months)', 'Overall_Survival_Status',
       'Other_Patient_ID',
       'American_Joint_Committee_on_Cancer_Metastasis_Stage_Code',
       'Neoplasm_Disease_Lymph_Node_Stage_American_Joint_Committee_on_Cancer_Code',
       'American_Joint_Committee_on_Cancer_Tumor_Stage_Code',
       'Person_Neoplasm_Cancer_Status', 'Progress_Free_Survival_(Months)',
       'Progression_Free_Status', 'Primary_Lymph_Node_Presentation_Assessment',
       'Prior_Diagnosis', 'Race_Category', 'Radiation_Therapy',
       'Ragnum_Hypoxia_Score', 'Number_of_Samples_Per_Patient', 'Sample_Type',
       'Sex', 'Somatic_Status', 'Subtype', 'Tumor_Break_Load',
       'Tissue_Prospective_Collection_Indicator',
       'Tissue_Retrospective_Collection_Indicator', 'Tissue_Source_Site',
       'Tissue_Source_Site_Code', 'TMB_(nonsynonymous)',
       'Tumor_Disease_Anatomic_Site', 'Tumor_Type', 'Patient_Weight',
       'Winter_Hypoxia_Score'],
      dtype='str')

In [29]:
non_predictor = ['Study_ID', 'Patient_ID', 'Sample_ID', 'Patient_Weight', 
                'Cancer_Type', 'Cancer_Type_Detailed', 'Sex', 'Number_of_Samples_Per_Patient', 
                'American_Joint_Committee_on_Cancer_Metastasis_Stage_Code', 
                'Primary_Lymph_Node_Presentation_Assessment', 'Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code', 
                'American_Joint_Committee_on_Cancer_Publication_Version_Type', 
                'Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code', 'TCGA_PanCanAtlas_Cancer_Type_Acronym',
                'Last_Alive_Less_Initial_Pathologic_Diagnosis_Date_Calculated_Day_Value', 'Disease-specific_Survival_status',
                'Ethnicity_Category', 'Neoplasm_Histologic_Grade', 'Neoadjuvant_Therapy_Type_Administered_Prior_To_Resection_Text', 'ICD-10_Classification', 'International_Classification_of_Diseases_for_Oncology,_Third_Edition_ICD-O-3_Histology_Code',
                'International_Classification_of_Diseases_for_Oncology,_Third_Edition_ICD-O-3_Site_Code', 
                'Informed_consent_verified', 'Oncotree_Code', 'Other_Patient_ID',
                'American_Joint_Committee_on_Cancer_Metastasis_Stage_Code', 'Primary_Lymph_Node_Presentation_Assessment', 
                'Race_Category', 'Number_of_Samples_Per_Patient', 'Sample_Type',
                'Somatic_Status', 'Subtype', 'Tissue_Source_Site', 'Tissue_Prospective_Collection_Indicator',
       'Tissue_Retrospective_Collection_Indicator', 'Tissue_Source_Site_Code', 'Tumor_Disease_Anatomic_Site']

In [10]:
prostate_cancer['Patient_Weight'].isna().sum()

np.int64(494)

In [22]:
prostate_cancer['Disease_Free_Status'].value_counts()

Disease_Free_Status
0:DiseaseFree            304
1:Recurred/Progressed     30
Name: count, dtype: int64

In [23]:
prostate_cancer['Disease_Free_(Months)'].value_counts()

Disease_Free_(Months)
25.183286    3
21.961403    3
30.936647    3
24.032613    2
13.019035    2
            ..
12.427261    1
16.964198    1
12.164250    1
13.479304    1
4.339678     1
Name: count, Length: 307, dtype: int64

Certain columns were dropped before data splitting because they only contained NA values, had little or no variance, or were not useful for predicting.

### Notes about features 
- Aneuploidy score: measures the total number of chromosome arm gains or losses within a tumor. Ranges from 0-39. A higher score indicates more "chaos" in the genome and often more aggressive tumors. 
- Birth_from_Initial_Pathologic_Diagnosis_Date: Time interval from a person's date of birth to the date of initial pathologic diagnosis, represented as a calculated number of days.

New_Neoplasm_Event_Post_Initial_Therapy_Indicator: Time interval from a person's date of birth to the date of initial pathologic diagnosis, represented as a calculated number of days.

Neoplasm_Disease_Lymph_Node_Stage_American_Joint_Committee_on_Cancer_Code: The codes that represent the stage of cancer based on the nodes present (N stage) according to criteria based on multiple editions of the AJCC's Cancer Staging Manual.

Buffa_Hypoxia_Score: a molecular tool used to quantify the level of oxygen deprivation (hypoxia) within tumors. Measures the activity of genes regulated by low oxygen, high scores are associated with poorer prognosis 

Ragnum_Hypoxia_Score: Measures oxygenation levels particularly in prostate cancer.

Disease_Free_(Months): Amount of time in remission. Likely will be predictor variable

In [33]:
prostate_cancer = prostate_cancer.drop(columns =non_predictor)

In [34]:
prostate_cancer.describe()

,Diagnosis_Age,Aneuploidy_Score,Buffa_Hypoxia_Score,Last_Communication_Contact_from_Initial_Pathologic_Diagnosis_Date,Birth_from_Initial_Pathologic_Diagnosis_Date,Disease_Free_(Months),Months_of_disease-specific_survival,Fraction_Genome_Altered,MSI_MANTIS_Score,MSIsensor_Score,Mutation_Count,Overall_Survival_(Months),Progress_Free_Survival_(Months),Ragnum_Hypoxia_Score,Tumor_Break_Load,TMB_(nonsynonymous),Winter_Hypoxia_Score
count,494.000000,471.000000,333.000000,486.000000,483.000000,334.000000,494.000000,489.000000,494.000000,494.000000,491.000000,494.000000,494.000000,333.000000,491.000000,494.000000,333.000000
mean,61.022267,2.528662,-26.627628,1080.135802,-22486.853002,35.656569,35.731337,0.090438,0.315634,0.063016,43.682281,35.731337,31.661258,-18.402402,76.648676,1.561606,-30.840841
std,6.844070,4.023697,8.810219,783.439310,2486.124360,24.411817,25.967482,0.101369,0.027996,0.467399,283.225627,25.967482,24.941887,6.183460,105.879819,9.490350,11.925038
min,41.000000,0.000000,-43.000000,0.000000,-28721.000000,1.873952,0.756156,0.000000,0.251800,0.000000,1.000000,0.756156,0.756156,-28.000000,0.000000,0.000000,-62.000000
25%,56.000000,0.000000,-33.000000,517.500000,-24293.500000,19.413486,17.227208,0.017400,0.303350,0.000000,20.000000,17.227208,13.832725,-22.000000,25.000000,0.675000,-38.000000
50%,61.000000,1.000000,-29.000000,924.000000,-22626.000000,30.328435,30.377749,0.063200,0.320950,0.000000,26.000000,30.377749,25.692869,-20.000000,53.000000,0.900000,-32.000000
75%,66.000000,3.000000,-21.000000,1463.250000,-20746.500000,45.665253,48.106322,0.121600,0.330900,0.020000,33.000000,48.106322,44.794030,-16.000000,90.000000,1.200000,-24.000000
max,78.000000,26.000000,11.000000,5024.000000,-15330.000000,165.170793,165.170793,0.578200,0.543800,7.580000,6230.000000,165.170793,165.170793,20.000000,1135.000000,208.633333,22.000000

In [35]:
prostate_cancer.columns

Index(['Diagnosis_Age', 'Aneuploidy_Score', 'Buffa_Hypoxia_Score',
       'Last_Communication_Contact_from_Initial_Pathologic_Diagnosis_Date',
       'Birth_from_Initial_Pathologic_Diagnosis_Date', 'Disease_Free_(Months)',
       'Disease_Free_Status', 'Months_of_disease-specific_survival',
       'Form_completion_date', 'Fraction_Genome_Altered',
       'Genetic_Ancestry_Label', 'In_PanCan_Pathway_Analysis',
       'MSI_MANTIS_Score', 'MSIsensor_Score', 'Mutation_Count',
       'New_Neoplasm_Event_Post_Initial_Therapy_Indicator',
       'Overall_Survival_(Months)', 'Overall_Survival_Status',
       'Neoplasm_Disease_Lymph_Node_Stage_American_Joint_Committee_on_Cancer_Code',
       'American_Joint_Committee_on_Cancer_Tumor_Stage_Code',
       'Person_Neoplasm_Cancer_Status', 'Progress_Free_Survival_(Months)',
       'Progression_Free_Status', 'Prior_Diagnosis', 'Radiation_Therapy',
       'Ragnum_Hypoxia_Score', 'Tumor_Break_Load', 'TMB_(nonsynonymous)',
       'Tumor_Type', 'Winter_Hypoxia_Score'],
      dtype='str')

I am thinking about doing one regression problem and one classification problem.

In [41]:
prostate_cancer.columns = prostate_cancer.columns.str.replace(r'[\(\)]', '', regex=True)

In [42]:
prostate_cancer.dtypes

Diagnosis_Age                                                                  int64
Aneuploidy_Score                                                             float64
Buffa_Hypoxia_Score                                                          float64
Last_Communication_Contact_from_Initial_Pathologic_Diagnosis_Date            float64
Birth_from_Initial_Pathologic_Diagnosis_Date                                 float64
Disease_Free_Months                                                          float64
Disease_Free_Status                                                              str
Months_of_disease-specific_survival                                          float64
Form_completion_date                                                             str
Fraction_Genome_Altered                                                      float64
Genetic_Ancestry_Label                                                           str
In_PanCan_Pathway_Analysis                                                       str
MSI_MANTIS_Score                                                             float64
MSIsensor_Score                                                              float64
Mutation_Count                                                               float64
New_Neoplasm_Event_Post_Initial_Therapy_Indicator                                str
Overall_Survival_Months                                                      float64
Overall_Survival_Status                                                          str
Neoplasm_Disease_Lymph_Node_Stage_American_Joint_Committee_on_Cancer_Code        str
American_Joint_Committee_on_Cancer_Tumor_Stage_Code                              str
Person_Neoplasm_Cancer_Status                                                    str
Progress_Free_Survival_Months                                                float64
Progression_Free_Status                                                          str
Prior_Diagnosis                                                                  str
Radiation_Therapy                                                                str
Ragnum_Hypoxia_Score                                                         float64
Tumor_Break_Load                                                             float64
TMB_nonsynonymous                                                            float64
Tumor_Type                                                                       str
Winter_Hypoxia_Score                                                         float64
dtype: object